### ISSUE TITLE
Request for a valid README file

### ISSUE THREAD

**Issue by hakbar0** [oliverabrahams/prometheus-grafana#1]
Hello oliverabrahams, I hope you're doing well. I just wanted to reach out and say that I am a big fan of your work. However, I noticed that the README file for your project is not up-to-date or detailed enough. It would be greatly appreciated if you could take some time to make a valid README file that clearly explains the purpose, usage and installation instructions for your project. This will help others understand and use your project more easily. Thanks for all the great work you do!

**Comment by oliverabrahams** [comment]
Thanks so much for your feedback, this is done now
